# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesAndBugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('TO DO', 'To do'), ('DOING', 'Doing'), ('DONE', 'Done')], default='TO DO', max_length=5)),
                ('type', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature')], max_length=20)),
                ('upvotes', models.IntegerField()),
                ('group', models.CharField(max_length=20)),
            ],
        ),
    ]
