# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0032_auto_20190419_1847'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='bug_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='bug_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bugs.Bugs'),
        ),
    ]
