# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_remove_comments_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(default='Anon', max_length=30),
        ),
    ]
