# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_comments_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(default='heelo'),
            preserve_default=False,
        ),
    ]
