# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 12:51
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_auto_20190421_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=30),
        ),
    ]
