# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 01:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0017_auto_20190421_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
