# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0019_auto_20190510_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='bug_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bugs.Bugs'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
