# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='user',
            field=models.CharField(default='admin', max_length=40),
            preserve_default=False,
        ),
    ]
