# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20190506_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='user_id',
        ),
    ]
