# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='image_carousel2',
            field=models.ImageField(default='Photo not available', upload_to='images'),
        ),
        migrations.AddField(
            model_name='features',
            name='image_carousel3',
            field=models.ImageField(default='Photo not available', upload_to='images'),
        ),
        migrations.AddField(
            model_name='features',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Doing', 'Doing'), ('To do', 'To do')], default='To do', max_length=14),
        ),
        migrations.AddField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('World', 'World'), ('Skills', 'Skills'), ('Item', 'Item'), ('Quests', 'Quests')], default='Item', max_length=6),
        ),
    ]
