# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available now!'), ('DOING', 'Doing'), ('TODO', 'To do')], default='TODO', max_length=14),
        ),
        migrations.AddField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('ITEM', 'Item'), ('QUESTS', 'Quests'), ('SKILLS', 'Skills'), ('WORLD', 'World')], default='ITEM', max_length=6),
        ),
    ]
