# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20190411_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='image_carousel1',
            field=models.ImageField(default='Photo not available', upload_to='images'),
        ),
        migrations.AddField(
            model_name='features',
            name='image_carousel2',
            field=models.ImageField(default='Photo not available', upload_to='images'),
        ),
        migrations.AddField(
            model_name='features',
            name='image_carousel3',
            field=models.ImageField(default='Photo not available', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('TODO', 'To do'), ('AVAILABLE', 'Available'), ('DOING', 'Doing')], default='TODO', max_length=14),
        ),
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('WORLD', 'World'), ('QUESTS', 'Quests'), ('ITEM', 'Item'), ('SKILLS', 'Skills')], default='ITEM', max_length=6),
        ),
    ]
