# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0002_auto_20190417_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='user_liked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('World', 'World'), ('Item', 'Item'), ('Quests', 'Quests'), ('Skills', 'Skills')], default='Item', max_length=6),
        ),
    ]
