# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0003_auto_20190418_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('Doing', 'Doing'), ('To do', 'To do'), ('Available', 'Available')], default='To do', max_length=14),
        ),
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Item', 'Item'), ('Quests', 'Quests'), ('Skills', 'Skills'), ('World', 'World')], default='Item', max_length=6),
        ),
        migrations.RemoveField(
            model_name='features',
            name='user_liked',
        ),
        migrations.AddField(
            model_name='features',
            name='user_liked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
