# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20190416_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='image_carousel1',
        ),
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('QUESTS', 'Quests'), ('SKILLS', 'Skills'), ('WORLD', 'World'), ('ITEM', 'Item')], default='ITEM', max_length=6),
        ),
    ]
