# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20190418_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Quests', 'Quests'), ('Skills', 'Skills'), ('World', 'World'), ('Item', 'Item')], default='Item', max_length=6),
        ),
    ]
