# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20190418_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Items', 'Item'), ('Worlds', 'World'), ('Quests', 'Quests'), ('Skills', 'Skills')], default='Item', max_length=6),
        ),
    ]
