# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20190417_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('To do', 'To do'), ('Doing', 'Doing')], default='To do', max_length=14),
        ),
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Skills', 'Skills'), ('World', 'World'), ('Quests', 'Quests'), ('Item', 'Item')], default='Item', max_length=6),
        ),
    ]
