# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0022_auto_20190420_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('To do', 'To do'), ('Doing', 'Doing')], default='To do', max_length=14),
        ),
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Worlds', 'World'), ('Quests', 'Quests'), ('Items', 'Item'), ('Skills', 'Skills')], default='Items', max_length=6),
        ),
    ]
