# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0023_auto_20190420_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('Doing', 'Doing'), ('Available', 'Available')], default='To do', max_length=14),
        ),
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Skills', 'Skills'), ('Worlds', 'World'), ('Quests', 'Quests'), ('Items', 'Item')], default='Items', max_length=6),
        ),
    ]
