# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0030_auto_20190420_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Worlds', 'World'), ('Quests', 'Quests'), ('Items', 'Item'), ('Skills', 'Skills')], default='Items', max_length=6),
        ),
    ]
