# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 15:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0041_auto_20190422_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Worlds', 'World'), ('Quests', 'Quests'), ('Items', 'Item'), ('Skills', 'Skills')], default='Items', max_length=6),
        ),
        migrations.AlterField(
            model_name='features',
            name='user_liked',
            field=models.ManyToManyField(default=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL),
        ),
    ]
