# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0042_auto_20190422_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Worlds', 'World'), ('Quests', 'Quests'), ('Skills', 'Skills'), ('Items', 'Item')], default='Items', max_length=6),
        ),
    ]
