# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0043_auto_20190423_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('Doing', 'Doing'), ('Available', 'Available'), ('To do', 'To do')], default='To do', max_length=14),
        ),
    ]
