# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0045_auto_20190428_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Doing', 'Doing'), ('To do', 'To do')], default='To do', max_length=14),
        ),
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Items', 'Item'), ('Worlds', 'World'), ('Quests', 'Quests'), ('Skills', 'Skills')], default='Items', max_length=6),
        ),
    ]
