# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0050_auto_20190428_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Skills', 'Skills'), ('Worlds', 'Worlds'), ('Quests', 'Quests'), ('Items', 'Items')], default='Items', max_length=6),
        ),
    ]
