# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0060_auto_20190506_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('Doing', 'Doing'), ('To do', 'To do'), ('Available', 'Available')], default='To do', max_length=14),
        ),
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Quests', 'Quests'), ('Worlds', 'Worlds'), ('Skills', 'Skills'), ('Items', 'Items')], default='Items', max_length=6),
        ),
    ]
