# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0087_auto_20190507_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Worlds', 'Worlds'), ('Skills', 'Skills'), ('Items', 'Items'), ('Quests', 'Quests')], default='Items', max_length=6),
        ),
    ]
