# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0105_auto_20190511_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Skills', 'Skills'), ('Worlds', 'Worlds'), ('Quests', 'Quests'), ('Items', 'Items')], default='Items', max_length=10),
        ),
    ]
