# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0109_auto_20190511_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('Doing', 'Doing'), ('Available', 'Available')], default='To do', max_length=14),
        ),
        migrations.AlterField(
            model_name='features',
            name='type',
            field=models.CharField(choices=[('Skills', 'Skills'), ('Worlds', 'Worlds'), ('Items', 'Items'), ('Quests', 'Quests')], default='Items', max_length=10),
        ),
    ]
