# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='price',
        ),
        migrations.AddField(
            model_name='bugs',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='bugs',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
