# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190411_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('FIXED', 'Fixed!'), ('DOING', 'Doing'), ('TODO', 'To do')], default='TODO', max_length=6),
        ),
    ]
