# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20190416_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('DOING', 'Doing'), ('FIXED', 'Fixed!'), ('TODO', 'To do')], default='TODO', max_length=6),
        ),
    ]
