# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0012_auto_20190417_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('TODO', 'To do'), ('DOING', 'Doing'), ('FIXED', 'Fixed!')], default='TODO', max_length=6),
        ),
    ]
