# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0018_auto_20190417_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('DOING', 'Doing'), ('TODO', 'To do'), ('FIXED', 'Fixed!')], default='TODO', max_length=6),
        ),
    ]
