# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0020_auto_20190418_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('World', 'World'), ('Item', 'Item'), ('Base game', 'Base game'), ('Quests', 'Quests'), ('Skills', 'Skills')], default='Base game', max_length=255),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Doing', 'Doing'), ('To do', 'To do')], default='TODO', max_length=6),
        ),
    ]
