# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0021_auto_20190418_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Quests', 'Quests'), ('World', 'World'), ('Item', 'Item'), ('Skills', 'Skills'), ('Base game', 'Base game')], default='Base game', max_length=6),
        ),
    ]
