# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0022_auto_20190418_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Item', 'Item'), ('Base game', 'Base game'), ('Skills', 'Skills'), ('Quests', 'Quests'), ('World', 'World')], default='Base game', max_length=10),
        ),
    ]
