# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0025_auto_20190419_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Doing', 'Doing'), ('Fixed', 'Fixed'), ('To do', 'To do')], default='To do', max_length=6),
        ),
    ]
