# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0028_auto_20190419_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Worlds', 'Worlds'), ('Base game', 'Base game'), ('Items', 'Items'), ('Quests', 'Quests'), ('Skills', 'Skills')], default='Base game', max_length=10),
        ),
    ]
