# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0032_auto_20190419_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Doing', 'Doing'), ('To do', 'To do')], default='To do', max_length=6),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Items', 'Items'), ('Skills', 'Skills'), ('Base game', 'Base game'), ('Worlds', 'Worlds'), ('Quests', 'Quests')], default='Base game', max_length=10),
        ),
    ]
