# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0039_auto_20190420_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Items', 'Items'), ('Skills', 'Skills'), ('Base game', 'Base game'), ('Quests', 'Quests'), ('Worlds', 'Worlds')], default='Base game', max_length=10),
        ),
    ]
