# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 01:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0048_auto_20190421_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Items', 'Items'), ('Base game', 'Base game'), ('Quests', 'Quests'), ('Skills', 'Skills'), ('Worlds', 'Worlds')], default='Base game', max_length=10),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='user_upvoted',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
