# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0049_auto_20190421_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugs',
            old_name='views',
            new_name='upvotes',
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Doing', 'Doing'), ('To do', 'To do'), ('Fixed', 'Fixed')], default='To do', max_length=6),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Skills', 'Skills'), ('Worlds', 'Worlds'), ('Quests', 'Quests'), ('Items', 'Items'), ('Base game', 'Base game')], default='Base game', max_length=10),
        ),
    ]
