# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0057_auto_20190422_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Worlds', 'Worlds'), ('Items', 'Items'), ('Quests', 'Quests'), ('Skills', 'Skills'), ('Base game', 'Base game')], default='Base game', max_length=10),
        ),
    ]
