# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0059_auto_20190426_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 28, 16, 2, 12, 270038), null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('To do', 'To do'), ('Doing', 'Doing')], default='To do', max_length=6),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Quests', 'Quests'), ('Skills', 'Skills'), ('Base game', 'Base game'), ('Worlds', 'Worlds'), ('Items', 'Items')], default='Base game', max_length=10),
        ),
    ]
