# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0060_auto_20190428_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 28, 16, 7, 34, 329543), null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Doing', 'Doing'), ('To do', 'To do'), ('Fixed', 'Fixed')], default='To do', max_length=6),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Items', 'Items'), ('Worlds', 'Worlds'), ('Base game', 'Base game'), ('Quests', 'Quests'), ('Skills', 'Skills')], default='Base game', max_length=10),
        ),
    ]
