# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0061_auto_20190428_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Doing', 'Doing'), ('To do', 'To do')], default='To do', max_length=6),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Skills', 'Skills'), ('Worlds', 'Worlds'), ('Items', 'Items'), ('Base game', 'Base game'), ('Quests', 'Quests')], default='Base game', max_length=10),
        ),
    ]
