# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0063_auto_20190428_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Doing', 'Doing'), ('To do', 'To do'), ('Fixed', 'Fixed')], default='To do', max_length=6),
        ),
    ]
