# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0076_auto_20190506_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Quests', 'Quests'), ('Skills', 'Skills'), ('Base game', 'Base game'), ('Worlds', 'Worlds'), ('Items', 'Items')], default='Base game', max_length=10),
        ),
    ]
