# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0081_auto_20190507_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Skills', 'Skills'), ('Worlds', 'Worlds'), ('Base game', 'Base game'), ('Quests', 'Quests'), ('Items', 'Items')], default='Base game', max_length=10),
        ),
    ]
