# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0103_auto_20190507_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('To do', 'To do'), ('Doing', 'Doing')], default='To do', max_length=6),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Items', 'Items'), ('Skills', 'Skills'), ('Base game', 'Base game'), ('Quests', 'Quests'), ('Worlds', 'Worlds')], default='Base game', max_length=10),
        ),
    ]
