# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0108_auto_20190510_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Quests', 'Quests'), ('Skills', 'Skills'), ('Worlds', 'Worlds'), ('Items', 'Items'), ('Base game', 'Base game')], default='Base game', max_length=10),
        ),
    ]
