# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0117_auto_20190511_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('Fixed', 'Fixed'), ('Doing', 'Doing')], default='To do', max_length=255),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('Skills', 'Skills'), ('Items', 'Items'), ('Quests', 'Quests'), ('Worlds', 'Worlds'), ('Base game', 'Base game')], default='Base game', max_length=255),
        ),
    ]
